DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE IF NOT EXISTS AUTHOR (
  ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
  LOGIN    VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  CONSTRAINT LOGIN_UNIQUE UNIQUE (LOGIN));
-- INSERT INTO AUTHOR (ID, LOGIN, PASSWORD) values(1, 'author1', 'pass1');
-- INSERT INTO AUTHOR (ID, LOGIN, PASSWORD) values(2, 'author2', 'pass2');
-- INSERT INTO AUTHOR (ID, LOGIN, PASSWORD) values(3, 'author3', 'pass3');

DROP TABLE IF EXISTS DOCUMENT;
CREATE TABLE IF NOT EXISTS DOCUMENT (
  ID            BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  AUTHOR_ID     BIGINT                            NOT NULL,
  DOCUMENT_NAME CHAR(20)                          NOT NULL,
  DESCRIPTION   CLOB,
  CONSTRAINT AUTHOR_DOCUMENT FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID) ON DELETE CASCADE ON UPDATE CASCADE);

DROP TABLE IF EXISTS VERSION;
CREATE TABLE IF NOT EXISTS VERSION (
  ID                  BIGINT AUTO_INCREMENT PRIMARY KEY,
  DOCUMENT_ID         BIGINT       NOT NULL,
  AUTHOR_ID           BIGINT       NOT NULL,
  DATE                DATETIME     NOT NULL,
  VERSION_DESCRIPTION CLOB,
  DOCUMENT_PATH       VARCHAR(255) NOT NULL,
  CONSTRAINT DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT AUTHOR_VERSION FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID) ON DELETE CASCADE ON UPDATE CASCADE

);
